### PR TITLE
QOL improvements + multi monitor support

### PR DESCRIPTION
**Pull request by gallantcrusader**
(first time doing this sorry if this is not how I should do this) Fixed a bug in eww where the settings panel could not open due to typo. Allowed the moving of windows using Super + Shift + arrow keys (so you can move windows between monitors). fixed up icon spacing in tint2 and added the ability to spawn apps by right clicking icons. added a screen shot utility that you can use by pressing Super + Shift + S (have to move wackysnap to a bin folder, made by manilarome) 'maim' is a dependency.

### CODE REVIEW

**Comment by mngshm** [comment]
You can see this PR has conflicts which should be resolved :)

**Comment by gallantcrusader** [comment]
> You can see this PR has conflicts which should be resolved :) 

Not at my computer right now, but will do.

**Comment by mngshm** [comment]
Hey mahn what's that doom zsh and polybar. I think you're doing smth wrong. You forked repo and you added your stuff for yourself but you don't need to make a pr. Actually I don't use zsh I don't use bash I use mksh and i didn't use doom Emacs in the screenshot and i don't use Emacs much. 

Let me know if you pushed those stuff for your fork of repo

**Comment by gallantcrusader** [comment]
Yeah no, that was for my own stuff, I'm not going to contribute my apologies.

**Pull request closed without merging**
